name: "Setup Environment"
description: "Set up the pre-compiled environment"

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Foundry toolchain
      uses: actions/cache@v3
      with:
        path: ~/.foundry
        key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
        restore-keys: |
          ${{ runner.os }}-foundry-

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly-e52076714ace23c7a68e14f0048a40be3c6c8f0b

    - name: Cache Foundry build outputs
      id: cache-foundry-build
      uses: actions/cache@v3
      with:
        path: |
          artifacts/forge-cache
          artifacts/foundry
        key: ${{ runner.os }}-foundry-build-${{ hashFiles('foundry.toml', 'remappings.txt', 'lib/**', 'proposals/**', 'crv-rewards/**') }}
        restore-keys: |
          ${{ runner.os }}-foundry-build-

    - name: Clean Contracts
      if: steps.cache-foundry-build.outputs.cache-hit != 'true'
      run: forge clean
      shell: bash

    - name: Compile Proposals
      run: forge compile --contracts proposals/
      shell: bash

    - name: Compile MultiRewarder
      run: forge compile --contracts crv-rewards/
      shell: bash

    - name: Compile Contracts
      run: forge build
      shell: bash
